### ISSUE TITLE
Add POT support

### ISSUE THREAD

**Issue by AndreySV** [transifex/openformats#71]
If messages.pot is used as source file for auto-update on transifex.com, update returns following error "Found empty msgid."

As a workaround we've generated English translation PO file and put it into source repository. This is suboptimal, because now we have English PO file and messages.pot template file in the repo.
It'd be really nice to have support of POT files, because POT (PO template) files are designed to be source files for translation.

**Comment by nelefth** [comment]
@AndreySV please let me further elaborate on this in order to help you understand better how this works.

Let's assume that you have the following source file: 

msgid "key1"
msgstr "string#1"

msgid "key2"
msgstr ""

If you try to upload it to Transifex, the following error message will appear: 

"The entry with msgid `key2` includes an empty msgstr. Provide a value and try again."

However, if your source file looks like this: 

msgid "key1"
msgstr ""

msgid "key2"
msgstr "string#2"

the error message you will get will be the following one: 

"A non-empty msgstr was found on the entry with msgid `key2`. Remove and try again. "

So, as you can see, our .po handler takes the way the first string is formatted into account in order to parse the file as a .po or as a .pot file. 

The difference between these file formats is mentioned in our FAQ section [here](https://docs.transifex.com/faq/all#whats-the-difference-using-a-po-and-pot-file-as-a-source-file). 
 
Does the above explanation help?

**Comment by AndreySV** [comment]
Does it skip messages.pot header? Because in header msgstr is not empty always.

Second question is, does transifex detects POT/PO format only if the file is uploaded on transifex or this is used by auto-update from public URL as well?

**Comment by nelefth** [comment]
@AndreySV 

**Question #1**:
Does it skip messages.pot header? Because in header msgstr is not empty always.

**Answer**:
Yes

**Question #2**:
Second question is, does transifex detects POT/PO format only if the file is uploaded on transifex or this is used by auto-update from public URL as well?

**Answer**:
No matter the way you've decided to update your source file, the parser behaves the same way.
So, what I described in the previous post is also applied to the auto-update feature as well.

**Comment by AndreySV** [comment]
Interesting. Previously I had problems with pot and all works smoothly. Thanks. I close the issue.
